# Generated by Django 3.2.4 on 2021-06-10 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 22, 55, 11, 262623, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.TextField(choices=[('High', 'High'), ('Med', 'Medium'), ('Low', 'Low')], default='Low'),
        ),
    ]
